#!/usr/bin/env python3
"""
scrub_mcp_config.py
Read ~/.minimax/mcp.json, strip env + headers blocks, emit a public-safe YAML.

This is the critical safety step before pushing any MCP catalog to a public
GitHub repo. The mavis-runtime subtree MUST go through this script.

Rules:
  - Drop `env` blocks entirely (replace with a REDACTED marker).
  - Drop `headers` blocks entirely (replace with a REDACTED marker).
  - Strip query-string / path secrets in `url` fields by checking for
    `token=`, `api_key=`, `apikey=`, `key=`, `secret=` substrings.
  - Drop fields that are *only* an inline credential marker
    (e.g. `Authorization: Bearer ...` strings) if they ever appear.
  - Keep: name, type/transport, command, args, description, enabled,
    configured, builtin, timeout, url (after scrubbing).
  - Audit step at the end: print redacted-servers count, redacted-fields count,
    and a SHA-256 of the source file so the caller can log it.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

try:
    import yaml  # PyYAML
except ImportError:
    print("ERROR: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(2)


REDACTED = "<REDACTED — secrets stripped before commit>"


def scrub_server(name: str, server: dict) -> tuple[dict, list[str]]:
    """Return (scrubbed_server, audit_notes)."""
    notes: list[str] = []
    out = dict(server)

    # Drop env block.
    if "env" in out:
        env = out.pop("env")
        notes.append(f"{name}: dropped env ({len(env)} keys)")
        out["env"] = REDACTED  # leave a marker so readers know there was one.

    # Drop headers block (http transport only).
    if "headers" in out:
        hdr = out.pop("headers")
        notes.append(f"{name}: dropped headers ({len(hdr)} keys)")
        out["headers"] = REDACTED

    # Scrub url query secrets (be conservative: redact any url with token-shaped query).
    if "url" in out and isinstance(out["url"], str):
        url = out["url"]
        lowered = url.lower()
        if any(marker in lowered for marker in ("token=", "api_key=", "apikey=", "secret=", "password=")):
            notes.append(f"{name}: redacted url ({url[:60]}...)")
            out["url"] = REDACTED

    return out, notes


def main() -> int:
    ap = argparse.ArgumentParser(description="Scrub mcp.json for public export.")
    ap.add_argument("--source", default=r"C:\Users\admin\.minimax\mcp.json",
                    help="Path to live mcp.json")
    ap.add_argument("--out", default=r"C:\Users\admin\.minimax\projects\coding-shared\mavis-runtime-staging\mavis-runtime\config\mcp-servers.public.yaml",
                    help="Where to write the public YAML")
    ap.add_argument("--audit-out", default=r"C:\Users\admin\.minimax\projects\coding-shared\mavis-runtime-staging\audit-mcp.txt",
                    help="Where to write the audit log")
    args = ap.parse_args()

    src = Path(args.source)
    dst = Path(args.out)
    audit_path = Path(args.audit_out)

    if not src.exists():
        print(f"ERROR: source not found: {src}", file=sys.stderr)
        return 1

    raw = src.read_text(encoding="utf-8")
    src_sha = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    data = json.loads(raw)

    servers = data.get("mcpServers") or {}
    scrubbed: dict = {}
    audit: list[str] = []

    for name, srv in servers.items():
        if not isinstance(srv, dict):
            scrubbed[name] = srv
            continue
        cleaned, notes = scrub_server(name, srv)
        scrubbed[name] = cleaned
        audit.extend(notes)

    # Emit as a YAML list of server records, ordered, with stable keys.
    ordered_keys = ["name", "type", "transport", "enabled", "configured",
                    "builtin", "command", "args", "url", "headers",
                    "env", "description", "timeout"]

    def reorder(d: dict) -> dict:
        present = {k: d[k] for k in ordered_keys if k in d}
        extras = {k: v for k, v in d.items() if k not in present}
        return {**present, **extras}

    yaml_records = []
    for name, srv in scrubbed.items():
        rec = reorder({"name": name, **srv})
        yaml_records.append(rec)

    header = (
        "# mcp-servers.public.yaml\n"
        "# Public catalog of MCP servers used by the Mavis runtime.\n"
        f"# Source: {src}\n"
        f"# Source SHA-256: {src_sha}\n"
        "# Generated by: scripts/scrub_mcp_config.py\n"
        "# Any `env` or `headers` block has been replaced with a REDACTED marker.\n"
        "# Secrets in URLs (token=, api_key=, etc.) are also redacted.\n"
        "# DO NOT edit by hand — re-run the scrubber.\n"
    )

    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(yaml_records, f, sort_keys=False, allow_unicode=True,
                       default_flow_style=False, width=120)

    audit_path.parent.mkdir(parents=True, exist_ok=True)
    with audit_path.open("w", encoding="utf-8") as f:
        f.write(f"source: {src}\n")
        f.write(f"source_sha256: {src_sha}\n")
        f.write(f"server_count: {len(servers)}\n")
        f.write(f"redactions:\n")
        for line in audit:
            f.write(f"  - {line}\n")
        if not audit:
            f.write("  - (none — no env/headers/secrets detected)\n")

    print(f"OK: wrote {len(servers)} servers to {dst}")
    print(f"OK: audit log at {audit_path}")
    print(f"Redactions: {len(audit)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())